# Apa itu Numpy

- NumPy atau Numpy adalah library aljabar linear untuk Python
- Numpy sering digunakan dalam konteks AI & Data science.
- Numpy sangat cepat dan dibangun melalui Bahasa C

## Menginstall Numpy

- Direkomendasikan melalui Anaconda
- Anaconda prompt -> conda install numpy
- Command Line -> pip install numpy

Silahkan gunakan salah satu dari anaconda dan pip, jika menggunakan keduanya , sering terjadi error.

In [2]:
import numpy as np

angka = [1,2,3]
angkap = np.array(angka)

print(angkap)
print(angka*3)
print(angkap*3)

[1 2 3]
[1, 2, 3, 1, 2, 3, 1, 2, 3]
[3 6 9]


In [3]:
verlist = [[1,2,3],[4,5,6],[7,8,9]]
vernp = np.array(verlist)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,20,3)

array([ 0,  3,  6,  9, 12, 15, 18])

In [8]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [9]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [11]:
np.ones((2,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [18]:
np.linspace(0,8,10)

array([0.        , 0.88888889, 1.77777778, 2.66666667, 3.55555556,
       4.44444444, 5.33333333, 6.22222222, 7.11111111, 8.        ])

## Identity Matrix

In [19]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Numpy 2

In [4]:
# bilangan distribusi uniform (0-1)
np.random.rand(7)

array([0.95753359, 0.93593315, 0.41398033, 0.053072  , 0.31250743,
       0.27690705, 0.1607712 ])

In [5]:
# bilangan distribusi uniform (0-1) matriks 2 dimensi
np.random.rand(5,4)

array([[0.47251048, 0.6229745 , 0.17877775, 0.12282005],
       [0.76026519, 0.40277381, 0.37899294, 0.91362623],
       [0.24164326, 0.0209978 , 0.65587694, 0.20824092],
       [0.78884513, 0.67575253, 0.93703307, 0.34970109],
       [0.69491393, 0.90160661, 0.0487486 , 0.43559638]])

In [6]:
# bilangan distribusi normal ( gaussian )
np.random.randn(10)

array([ 0.57627969,  0.17910954,  0.22251177, -1.16363973,  1.38290581,
       -0.25488224,  1.40946662,  0.24810054,  0.57900718, -1.23462347])

In [7]:
# bilangan distribusi normal ( gaussian ) matriks 2 dimensi
np.random.randn(4,4)

array([[-0.44140577, -1.78297377, -1.08956792,  1.18627944],
       [-0.32323737,  0.30632977,  1.28511855,  0.68170682],
       [ 1.72449288,  1.35262486,  0.79547742, -1.20540701],
       [-1.49139229,  0.0544825 ,  0.26581012, -1.76333147]])

In [9]:
from numpy.random import randn, randint

randn(6,2)

array([[-0.68603431,  0.52200743],
       [ 0.81337762,  0.05189268],
       [ 1.32432218, -0.35297037],
       [-0.03035675, -0.95808007],
       [-0.66688679,  0.36760129],
       [-2.03048608,  0.73840378]])

In [12]:
randint(0,10,5)

array([1, 0, 1, 9, 8])

In [14]:
bilangan = randint(0,100,20)
print(bilangan)

[42 12 18 93 62  3 11  8 53 13 11  2 14 10 36 14  9 46 59 74]


In [16]:
bilangan.reshape(4,5)

array([[42, 12, 18, 93, 62],
       [ 3, 11,  8, 53, 13],
       [11,  2, 14, 10, 36],
       [14,  9, 46, 59, 74]])

In [24]:
coba = randint(0,10,20).reshape(5,4)
coba2 = coba.reshape(2,10)
print(coba)
print(coba2)

[[1 6 5 5]
 [3 1 0 7]
 [3 0 6 5]
 [1 4 7 7]
 [6 3 3 1]]
[[1 6 5 5 3 1 0 7 3 0]
 [6 5 1 4 7 7 6 3 3 1]]


In [31]:
coba1d = randint(0,100,20)
coba2d = randint(0,100,20).reshape(4,5)

print(coba1d)
print(coba2d)

print(coba1d.max())
print(coba2d.max())

print(coba1d.argmax())
print(coba2d.argmax())

print(coba1d.min())
print(coba2d.min())

print(coba1d.argmin())
print(coba2d.argmin())

[44 36 76 67 26 26 73 10 43 90 97 48 33 23 53  4 76 89 48 27]
[[54 47 60 38 74]
 [27 38 94 73 40]
 [14 52  6 73 28]
 [20  7  3 99 84]]
97
99
10
18
4
3
15
17


In [33]:
coba1d.shape

(20,)

In [34]:
coba2d.shape

(4, 5)

In [35]:
coba1d.dtype

dtype('int32')

In [36]:
coba2d.dtype

dtype('int32')

## Indexing di Numpy

In [49]:
cobalagi = np.arange(0,11)

print("coba lagi =",cobalagi)
print("cobalagi[6] berisi",cobalagi[6])
print("cobalagi[:6] berisi",cobalagi[:6])
print("cobalagi[5::] =",cobalagi[5::])
print("cobalagi[5::2] =",cobalagi[5::2])
print("cobalagi[::2] =",cobalagi[::2])

coba lagi = [ 0  1  2  3  4  5  6  7  8  9 10]
cobalagi[6] berisi 6
cobalagi[:6] berisi [0 1 2 3 4 5]
cobalagi[5::] = [ 5  6  7  8  9 10]
cobalagi[5::2] = [5 7 9]
cobalagi[::2] = [ 0  2  4  6  8 10]


In [52]:
cobalagi2 = cobalagi[:5]
print(cobalagi2)

cobalagi2[:] = 100
print(cobalagi2)

print(cobalagi) # cobalagi masih terlink dengan cobalagi2

[100 100 100 100 100]
[100 100 100 100 100]
[100 100 100 100 100   5   6   7   8   9  10]


In [55]:
# untuk mengassign cobalagi ke cobalagi2 tanpa link harusnya menggunakan copy()
cobalagi = np.arange(0,11)
cobalagi2 = cobalagi[:5].copy()
print(cobalagi2)

cobalagi2[:] = 100
print(cobalagi2)

print(cobalagi) # cobalagi sudah tidak terlink dengan cobalagi2

[0 1 2 3 4]
[100 100 100 100 100]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [60]:
bil2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(bil2d)
print(bil2d[0][0])
print(bil2d[0,0])


print(bil2d[1])
print(bil2d[1:2,1:])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
1
[4 5 6]
[[5 6]]


In [61]:
bil = np.arange(1,11)

print("bil adalah",bil)

bil adalah [ 1  2  3  4  5  6  7  8  9 10]


In [65]:
angkaT = bil>5

print(angkaT)
print(bil[angkaT])
print(bil[bil<3])

[False False False False False  True  True  True  True  True]
[ 6  7  8  9 10]
[1 2]


# Numpy 3

## Operasi di Numpy

In [66]:
import numpy as np

In [81]:
cobalist = list(range(0,11))
print(cobalist)
print(cobalist*2)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [80]:
coba = np.arange(0,11)

print(coba)
print(coba + 5)
print( coba + coba)
print(coba**2)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 5  6  7  8  9 10 11 12 13 14 15]
[ 0  2  4  6  8 10 12 14 16 18 20]
[  0   1   4   9  16  25  36  49  64  81 100]


In [85]:
print(coba/2)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


In [86]:
print(np.sqrt(coba))

[0.         1.         1.41421356 1.73205081 2.         2.23606798
 2.44948974 2.64575131 2.82842712 3.         3.16227766]


##  e (eksponen) = 2.7182

In [87]:
np.exp(coba)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [88]:
coba.max()

10

In [89]:
np.max(coba)

10

In [90]:
np.sin(coba)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [91]:
np.log(coba)

<ipython-input-91-953d5638885c>:1: RuntimeWarning: divide by zero encountered in log
  np.log(coba)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])

# Dokumentasi :

https://numpy.org/doc/stable/reference/ufuncs.html